import { catalog, BUSINESS_PHONE } from './src/data/catalog.js';
import { Cart } from './src/domain/Cart.js';
import { renderListItem, updateBottomSheet, renderCartPopover } from './src/ui/components.js';
import { initI18n } from './src/i18n.js';

// Initialize i18n (default to English)
await initI18n('en');

const cart = new Cart();
const listContainer = document.getElementById('menu-list');
const tabs = document.querySelectorAll('.tab');

// Try to load the images manifest (generated by scripts/process-images.js)
fetch('assets/images/manifest.json').then(r => r.json()).then(m => { window.__IMAGE_MANIFEST__ = m; }).catch(()=>{/* no manifest */});

// Inline the icons sprite if present (improves caching and allows <use>)
fetch('assets/icons/sprite.svg').then(r => r.text()).then(svg => {
    const div = document.createElement('div');
    div.style.display = 'none';
    div.innerHTML = svg;
    document.body.insertBefore(div, document.body.firstChild);
}).catch(()=>{/* no sprite yet */});

// Dark mode removed; site uses single light palette

// Renderiza una versión simplificada con solo 3 cards (Niños, Adultos, Extras)
function loadItems(category) {
    listContainer.innerHTML = ''; // Limpiar lista
    const fragment = document.createDocumentFragment();

    const phone = BUSINESS_PHONE;

    function openWhatsApp(message) {
        const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
        window.open(url, '_blank');
    }

    function createCard({ title, desc, actions }) {
        const div = document.createElement('div');
        div.className = 'menu-item';

        const info = document.createElement('div');
        info.className = 'item-info';
        info.innerHTML = `<h3>${title}</h3><p class="item-desc">${desc || ''}</p>`;

        const controls = document.createElement('div');
        controls.style.display = 'flex';
        controls.style.flexDirection = 'column';
        controls.style.gap = '8px';
        controls.style.alignItems = 'flex-end';

        if (actions && actions.length) {
            const row = document.createElement('div');
            row.style.display = 'flex';
            row.style.gap = '8px';
            actions.forEach(a => {
                const btn = document.createElement('button');
                btn.className = 'btn-primary';
                btn.textContent = a.label;
                btn.addEventListener('click', (e) => { e.stopPropagation(); openWhatsApp(a.message); });
                row.appendChild(btn);
            });
            controls.appendChild(row);
        }

        div.appendChild(info);
        div.appendChild(controls);
        return div;
    }

    // Niños: solo opción Corte
    fragment.appendChild(createCard({
        title: (window.i18n && window.i18n.t) ? window.i18n.t('cards.kids.title') : 'Niños',
        desc: (window.i18n && window.i18n.t) ? window.i18n.t('cards.kids.desc') : 'Cortes para los más pequeños. Ambiente amigable y seguro.',
        actions: [ { label: (window.i18n && window.i18n.t) ? window.i18n.t('cards.kids.actions.cut.label') : 'Corte', message: (window.i18n && window.i18n.t) ? window.i18n.t('cards.kids.actions.cut.message') : 'Hola, quisiera reservar un corte para niño.' } ]
    }));

    // Adultos: Corte y Corte con barba
    fragment.appendChild(createCard({
        title: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.title') : 'Adultos',
        desc: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.desc') : 'Cortes clásicos y modernos. También ofrecemos arreglo de barba.',
        actions: [
            { label: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.actions.cut.label') : 'Corte', message: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.actions.cut.message') : 'Hola, quisiera reservar un corte (adulto).' },
            { label: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.actions.cut_beard.label') : 'Corte + Barba', message: (window.i18n && window.i18n.t) ? window.i18n.t('cards.adults.actions.cut_beard.message') : 'Hola, quisiera reservar un corte con barba (adulto).' }
        ]
    }));

    // Extras: recuadro con brief description y contacto
    fragment.appendChild(createCard({
        title: (window.i18n && window.i18n.t) ? window.i18n.t('cards.extras.title') : 'Extras',
        desc: (window.i18n && window.i18n.t) ? window.i18n.t('cards.extras.desc') : 'Servicios adicionales: tintes, tratamientos capilares, arreglo de cejas y más. Contáctanos para más detalles.',
        actions: [ { label: (window.i18n && window.i18n.t) ? window.i18n.t('cards.extras.actions.contact.label') : 'Contactar', message: (window.i18n && window.i18n.t) ? window.i18n.t('cards.extras.actions.contact.message') : 'Hola, quisiera información sobre extras.' } ]
    }));

    listContainer.appendChild(fragment);
}

// Lógica de Tabs
tabs.forEach(tab => {
    tab.addEventListener('click', () => {
        // Remover clase active de todos
        tabs.forEach(t => t.classList.remove('active'));
        // Activar clickeado
        tab.classList.add('active');
        // Cargar items
        loadItems(tab.dataset.cat);
    });
});

// Carga inicial
loadItems('all');

// Abrir/cerrar popover al hacer click en el resumen (badge/total)
const cartSummary = document.getElementById('cart-summary') || document.querySelector('.cart-summary');
if (cartSummary) {
    cartSummary.addEventListener('click', (e) => {
        e.stopPropagation();
        const pop = document.getElementById('cart-popover');
        if (pop && pop.classList.contains('visible')) {
            pop.classList.remove('visible');
            cartSummary.setAttribute('aria-expanded', 'false');
        } else {
            renderCartPopover(cart);
            cartSummary.setAttribute('aria-expanded', 'true');
        }
    });
}

// Cerrar popover con ESC (accesibilidad)
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
        const pop = document.getElementById('cart-popover');
        const cs = document.getElementById('cart-summary');
        if (pop && pop.classList.contains('visible')) {
            pop.classList.remove('visible');
            if (cs) cs.setAttribute('aria-expanded', 'false');
        }
    }
});

// Delegación para botones de "retirar" (data-remove)
document.addEventListener('click', (e) => {
    const rem = e.target.closest('[data-remove]');
    if (rem) {
        const pid = rem.dataset.remove;
        const id = isNaN(Number(pid)) ? pid : Number(pid);
        cart.remove(id);
        updateBottomSheet(cart.getTotal(), cart.items.length);
        renderCartPopover(cart);
    }
});

// Checkout
document.getElementById('checkout-btn').addEventListener('click', () => {
    const url = cart.generateWhatsAppLink(BUSINESS_PHONE);
    window.open(url, '_blank');
});

// Wire footer contact link to BUSINESS_PHONE with a friendly message
const footerContact = document.getElementById('footer-contact');
if (footerContact) {
    const msg = encodeURIComponent("Hi, I can't find something on the menu. Can you help?");
    footerContact.href = `https://wa.me/${BUSINESS_PHONE}?text=${msg}`;
}